### ISSUE TITLE
how can i get list of all addresses having balance ?

### ISSUE THREAD

**Issue by rawmaterials** [alecalve/python-bitcoin-blockchain-parser#16]
i.e unspent outputs.

thanks

**Comment by alecalve** [comment]
To get unspent outputs you basically need to go through the blockchain and recreate the UTXO set at the point at which you want the balances.

The naive way would be to go through all blocks in historical order and maintain an internal set of unspent outputs, updating it at every block. However, this is not really practical as it is quite slow and memory intensive (last time I tried, I couldn't do it this way on a 16GB RAM machine). 

A smarter way would be to chunk the blockchain into manageable size pieces, and for each : 
- create a chunk-level UTXO set
- maintain a list of outputs that were spent in that chunk not created in it

Once all the chunks have been processed this way, you just need to combine all the chunk-level UTXO sets into a global UTXO set and then remove from it the lists of spent outputs. This can be done on disk instead of in memory.

**Comment by skorokithakis** [comment]
How is this possible to do if you can't get the input addresses? I'm trying to do the same but I can't find the input address anywhere, only the output addresses.

**Comment by agoora** [comment]
How can i get list of all addresses and hash160, having positive balance ?

**Comment by educob** [comment]
You have to go through every block and decode the scriptPubKey script to find the address behind it.
No easy task.
