### ISSUE TITLE
how do you get input address?

### ISSUE THREAD

**Issue by beanhedge** [alecalve/python-bitcoin-blockchain-parser#44]
output.addresses works great but input doesn't have an addresses property?

**Comment by alecalve** [comment]
Bitcoin transactions refer to previous outputs by the tuple (transaction hash, output index). In order to get the input address, you have to resolve which output the tuple points to. 

Most explorers do this and maintain a large database with this information. For simplicity sake, this project doesn't do this out of the box, so you'd have to maintain that database of (transaction hash, output index, output value, output address) yourself.

**Comment by Congyuwang** [comment]
This library support finding input address: https://github.com/Congyuwang/Py-Bitcoin-Explorer
`pip install bitcoin_explorer`

With `connected=True`, blocks are iterated in sequential order & input addresses are attached.
```python
import bitcoin_explorer as bex

# parse the same path as `--datadir` argument for `bitcoind`.
db = bex.BitcoinDB("~/Bitcoin")

for block in db.get_block_iter_range(end=700000, connected=True):
    do_something_with(block)
```
