### ISSUE TITLE
why there isn't a member variable `self.value` in class `Input`?

### ISSUE THREAD

**Issue by bosskwei** [alecalve/python-bitcoin-blockchain-parser#49]
Hi,
Why there isn't a member variable `self.value` or `self.satoshi` in class `Input` to indicate how much money the input address (or previous trans) spent? Without this value I could not know the balance of an address. Is that me who make something wrong?
Thanks

**Comment by alecalve** [comment]
Bitcoin transactions refer to previous outputs by the tuple (transaction hash, output index). In order to get the previous output value, you have to resolve which output the tuple points to.

Most explorers do this and maintain a large database with this information. For simplicity sake, this project doesn't do this out of the box, so you'd have to maintain that database of (transaction hash, output index, output value) yourself.

**Comment by bosskwei** [comment]
@alecalve Hi, Thanks for your reply, but I know this point, but a transaction may refers to lots of different previous outputs, how could I know how much satoshi of each of them?

**Comment by alecalve** [comment]
You just have to resolve the previous outputs in order.

Taking [this transaction](https://blockchain.info/tx/85fc20bce883c4f89f590f78316f5cf233d3323cd76230dddf2fdb540092947c) as an example, it has 2 inputs:

```json
[
  {
    "hash":"b6417e146b1930b14753a0520464bac21f99027b29bd5e256c7defd07c113bc1",
    "index":0
  },
  {
    "hash":"12f1af4a30af57c69d0d4c2db3435dad50f3a3b179d4a70a612c51dab61fac58",
    "index":1
  }
]
```

The first output (so index 0) of transaction [b641..3bc1](https://blockchain.info/tx/b6417e146b1930b14753a0520464bac21f99027b29bd5e256c7defd07c113bc1) has a value of 0.06 BTC, so the first input's value is 0.06 BTC.

The second output (index 1) of transaction [12f1..ac58](https://blockchain.info/tx/12f1af4a30af57c69d0d4c2db3435dad50f3a3b179d4a70a612c51dab61fac58) has a value of 0.04 BTC, so the second input's value is 0.04 BTC.

**Comment by bosskwei** [comment]
Thank you, now I have a thorough grasp of this problem.
