### ISSUE TITLE
Improve speed of Transaction generation

### ISSUE THREAD

**Issue by adnia** [alecalve/python-bitcoin-blockchain-parser#5]
Hi,

thank you for providing this nice blockchain parsing library!

I am using it to parse the whole blockchain and using debug prints and `cProfile`, I recognized that parsing one `*.blk` file roughly takes 40-50 seconds on my setup (I'm reading from an SSD and definitely have enough RAM). Of these 40-50 seconds, my program spends already 28 seconds in the `__init__()` function of `blockchain_parser.Transaction`.

Do you happen to know of any means to speed this up?
I also tried to use a C++ library before, which works considerably faster.

Thank you in advance for any response!

**Comment by alecalve** [comment]
Thank you for using this library.

I already used cProfile and came to the same conclusion as you. The time spent in this function is because most of the blockchain data is transactions and the `__init__` method of the `Transaction` class parses the transaction and its outputs/inputs.

As expected, C++ is considerably faster than Python, since it's compiled and not interpreted. Maybe using PyPy might help.
